import { z } from "zod";

export const UdfProductId = z.object({
    productId: z.number(),
}).array();

export const UdfWithoutProductId = z.object({
    brand: z.string().nullable(),
    features: z.string().array(),
    featuredImageUrl: z.string().nullable(),
    imageUrls: z.string().array(),
    length: z.number().nullable(),
    width: z.number().nullable(),
    height: z.number().nullable(),
    unit: z.string().nullable(),
    cadUrl: z.string().nullable(),
    catalogPageUrl: z.string().nullable(),
    dataSheetUrl: z.string().nullable(),
    userManualUrl: z.string().nullable(),
    ratingHp: z.number().nullable(),
    ratingHp2: z.string().nullable(),
    ratingKw: z.number().nullable(),
    maxSpeed: z.number().nullable(),
    speed2: z.string().nullable(),
    voltage: z.string().nullable(),
    phase: z.string().nullable(),
    current: z.string().nullable(),
    current2: z.string().nullable(),
    downThrust: z.string().nullable(),
    duty: z.string().nullable(),
    efficiency: z.string().nullable(),
    electricalType: z.string().nullable(),
    startingType: z.string().nullable(),
    framePrefix: z.string().nullable(),
    frameSize: z.string().nullable(),
    frameSuffix: z.string().nullable(),
    frameLength: z.number().nullable(),
    frameLengthMm: z.number().nullable(),
    frameMaterial: z.string().nullable(),
    frameType: z.string().nullable(),
    enclosureType: z.string().nullable(),
    rotation: z.string().nullable(),
    mountingType: z.string().nullable(),
    maxAmbient: z.string().nullable(),
    boxMounting: z.string().nullable(),
    baseDiameter: z.string().nullable(),
    shaftDiameter: z.string().nullable(),
    shaftDiameterMm: z.number().nullable(),
    shaftExtension: z.string().nullable(),
    shaftExtensionMm: z.number().nullable(),
    shaftType: z.string().nullable(),
    cDimMm: z.number().nullable(),
    cDimIn: z.number().nullable(),
    connectionDrawingNo: z.string().nullable(),
    deBearingSize: z.string().nullable(),
    deBearingType: z.string().nullable(),
    frequency: z.string().nullable(),
    hazardousLocation: z.string().nullable(),
    insulationClass: z.string().nullable(),
    ipCode: z.string().nullable(),
    kvaCode: z.string().nullable(),
    motorOrientation: z.string().nullable(),
    nemaDesign: z.string().nullable(),
    numPoles: z.string().nullable(),
    numSpeeds: z.string().nullable(),
    odeBearingSize: z.string().nullable(),
    odeBearingType: z.string().nullable(),
    outlineDrawingNo: z.string().nullable(),
    powerFactor: z.string().nullable(),
    resistanceMain: z.string().nullable(),
    serviceFactor: z.number().nullable(),
    thruBoltsExt: z.string().nullable(),
    overload: z.string().nullable(),
    certCe: z.boolean().nullable(),
    certCsa: z.boolean().nullable(),
    certUl: z.boolean().nullable(),
}).partial().array();

export const UdfBulkUpdateSchema = z.intersection(UdfProductId, UdfWithoutProductId)